In [2]:
# Manual Normalization

def norm_manuak(data):
     n_max = max(data)
     n_min = min(data)
     len_arr = len(data) #length of the entire data

     for i in range(0, len_arr):
          data[i] = (data[i] - n_min) / (n_max - n_min)

     return data

In [3]:
nilai = [10, 13, 14, 12]
nilai_norm = norm_manuak(nilai)
nilai_norm

[0.0, 0.75, 1.0, 0.5]

In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [6]:
data = [10, 15, 13, 14, 20, 30, 40, 28]
type(data)

list

In [8]:
data = [[10, 11], [11, 22]]
data = np.asarray(data)
data.shape

(2, 2)

In [10]:
data = [
     [100, 0.01],
     []
]
data = np.asarray(data)
data.shape

scaler = MinMaxScaler()

scaled = scaler.fit_transform(data)
scaled

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
def std_man(data):
     n_mean = np.mean(data)
     n_std = np.std(data)
     l_data = len(data)

     for i in range(0, l_data):
          data[i] = (data[i] - n_mean) / n_std

     return data

In [12]:
nilai = [10, 11,23,14,15,18,20]
nilai_std = std_man(nilai)
nilai_std

[-1.3344363375534447,
 -1.106605743337003,
 1.627361387260298,
 -0.42311396068767765,
 -0.1952833664712359,
 0.48820841617808935,
 0.9438696046109728]

In [13]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler

data = ([[100, 0.001],
          [8, 0.05],
          [50, 0.005],
          [88, 0.07],
          [4, 0.1]])

print ("Data asli: ")
print(data)

scaler = StandardScaler()

print ("Data transform hasil standarisasi: ")

scaled = scaler.fit_transform(data)
print(scaled)

Data asli: 
[[100, 0.001], [8, 0.05], [50, 0.005], [88, 0.07], [4, 0.1]]
Data transform hasil standarisasi: 
[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]


In [15]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

poli = [
     ["POLINEMA"],
     ["PENS"],
     ["PNJ"],
     ["POLBAN"],
     ["POLMANBABEL"]
]

poli_enc = oe.fit_transform(poli)
poli_enc

array([[3.],
       [0.],
       [1.],
       [2.],
       [4.]])

In [1]:
# one hot encoder
from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder()

poli = [
     ["POLINEMA"],
     ["PENS"],
     ["PNJ"],
     ["POLBAN"],
     ["POLMANBABEL"]
]

poli_enc = oh.fit_transform(poli)
poli_enc.toarray()

array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer()

dt = [
          {'name' : 'POLINEMA'},
          {'name' : 'PENS'},
          {'name' : 'PNJ'},
          {'name' : 'POLBAN'},
          {'name' : 'POLIJE'}

]

poli_dv = dv.fit_transform(dt)
poli_dv.toarray()

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [21]:
corpus = [
     'the house had a tiny little mouse',
     'the cat saw the mouse',
     'the mouse ran away from the house',
     'the cat finally ate the mouse',
     'the end of the mouse story'
]

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

vector = TfidfVectorizer(stop_words='english')
result = vector.fit_transform(corpus)
result = result.toarray()
result.shape

(5, 12)

In [27]:
vector.get_feature_names()

['ate',
 'away',
 'cat',
 'end',
 'finally',
 'house',
 'little',
 'mouse',
 'ran',
 'saw',
 'story',
 'tiny']

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
     'This is the first document',
     'This document is the second document.',
     'This is the third one',
     'And this is the fourth document ?'
]

vector = TfidfVectorizer(stop_words='english')
response = vector.fit_transform(corpus)
response.todense()

matrix([[1.        , 0.        , 0.        ],
        [0.78722298, 0.        , 0.61666846],
        [0.        , 0.        , 0.        ],
        [0.53802897, 0.84292635, 0.        ]])

In [1]:
import pandas as pd